routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
//Route::get('revisao', function () {
//return view('revisao');
//});

Route::resource('servicos', 'ServicoController');
Route::post('servicospesq', 'ServicoController@pesq')
        ->name('servicos.pesq');

Route::resource('usuarios', 'UsuarioController');
Route::post('usuariospesq', 'UsuarioController@pesq')
        ->name('usuarios.pesq');

Route::resource('funcionarios', 'FuncionarioController');
Route::post('funcioanriopesq', 'FuncionarioController@pesq')
        ->name('funcionarios.pesq');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

// Route::get('/home2', 'Home2Controller@index')->name('home2');

Route::get('/events', 'EventController@index');

// Route::resource('carros', 'Admin\CarroController');
//     Route::get('carrosgraf', 'Admin\CarroController@graf')
//             ->name('carros.graf');

// Route::get('/servicos', 'ServicoController@index')->name('servicos');
//
// Route::get('/usuarios', 'UsuarioController@index')->name('usuarios');
//
// Route::get('/funcionarios', 'FuncionarioController@index')->name('funcionario');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

resources/views/agenda_form.blade.php
@extends('adminlte::page')

@section('title', 'Consulta de Serviços')

@section('content_header')

<div class="container">

  <div class="row" style="margin-top: 10px">

  @if ($errors->any())
    <div class="col-sm-12 alert alert-danger">
      <ul>
      @foreach ($errors->all() as $error)
        <li>{{ $error }}</li>
      @endforeach
      </ul>
    </div>
  @endif

  <div class="col-sm-11">

  @if ($acao == 1)
    <h2>Inclusão de servicos</h2>
  @elseif ($acao == 2)
    <h2>Consulta de servicos</h2>
  @else
    <h2>Alteração de servicos</h2>
  @endif

  </div>
  <div class="col-sm-1">
  <a href="{{ route('servicos.index') }}" class="btn btn-info" role="button">
    Voltar</a>
  </div>
  </div>

  @if ($acao == 1)
    <form action="{{ route('servicos.store') }}" method="POST">
  @elseif ($acao == 3)
    <form action="{{ route('servicos.update', $reg->id) }}" method="POST">
    {{ method_field('PUT') }}
  @endif

    {{ csrf_field() }}

    <div class="form-group">
      <label for="nome">Nome:</label>
      <input type="text" class="form-control" id="nome" name="nome"
             value="{{ $reg->nome or old('nome') }}">
    </div>

    <div class="form-group">
      <label for="valor">Valor:</label>
      <input type="text" class="form-control" id="valor" name="valor"
             value="{{ $reg->valor or old('valor') }}">
    </div>

    <div class="form-group">
      <label for="tempo_duracao">Duração:</label>
      <input type="text" class="form-control" id="tempo_duracao" name="tempo_duracao"
             value="{{ $reg->tempo_duracao or old('tempo_duracao') }}">
    </div>

    <div class="form-group">
      <label for="descricao">Descrição:</label>
      <input type="text" class="form-control" id="descricao" name="descricao"
             value="{{ $reg->descricao or old('descricao') }}">
    </div>

    @if($acao == 1 or $acao == 3)
      <button type="submit" class="btn btn-primary">Enviar</button>
      <button type="reset" class="btn btn-success">Limpar</button>
    @endif

  </form>
@stop

resources/views/agenda_lista.blade.php
@extends('adminlte::page')

@section('title', 'Serviços')

@section('content_header')

<div class="container">

  <div class="row" style="margin-top: 10px">
  <div class="col-sm-6">
    <h2>Cadastro de servicos</h2>
  </div>

  <div class="col-sm-4">
     <form method="POST"
           class="form-inline"
           action="{{ route('servicos.pesq') }}">
       {{ csrf_field() }}
       <input type="text" class="form-control"
              name="palavra"
              placeholder="Palavra do filtro"> &nbsp;
       <input type="submit" class="btn btn-success"
              value="Ok">
     </form>
  </div>

  <div class="col-sm-2">
      <a href="{{ route('servicos.index') }}"
         class="btn btn-warning" role="button">
          Todos</a>

      <a href="{{ route('servicos.create') }}"
         class="btn btn-info" role="button">
           Novo</a>
  </div>

  </div>

  @if (session('status'))
  <div class="alert alert-success">
      {{ session('status') }}
  </div>
  @endif

  <table class="table table-hover">
    <thead>
      <tr>
        <th>Serviço</th>
        <th>Valor</th>
        <th>Duração</th>
        <th>Descrição</th>
        <th>Ações</th>
      </tr>
    </thead>
    <tbody>
      @forelse ($servicos as $p)
        <tr>
          <td>{{$p->nome}}</td>
          <td>{{$p->valor}}</td>
          <td>{{$p->tempo_duracao}}</td>
          <td>{{$p->descricao}}</td>
          <td>
           <a href="{{ route('servicos.show', $p->id) }}"
              class="btn btn-success btn-sm" role="button">Consultar</a>

           <a href="{{ route('servicos.edit', $p->id) }}"
              class="btn btn-warning btn-sm" role="button">Alterar</a>

           <form method="POST" action="{{ route('servicos.destroy', $p->id) }}"
                 style="display: inline-block;"
                 onsubmit="return confirm('Confirma Exclusão?') ">
            {{ method_field('DELETE') }}
            {{ csrf_field() }}
              <button type="submit" class="btn btn-danger btn-sm">
                Excluir</button>
           </form>

          </td>
        </tr>
      @empty
        <tr><td colspan=5>
          Não há servicos cadastrados
          ou com a palavra <b>{{ $palavra or '' }}</b>
          informada na pesquisa </td></tr>
      @endforelse
    </tbody>
  </table>

</div>

@stop

resources/views/fullcalender.blade.php
@extends('adminlte::page')



<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/2.2.7/fullcalendar.min.css"/>


@section('content')
<div class="container">
   <div class="row">
       <div class="col-md-8 col-md-offset-2">
           <div class="panel panel-default">
               <div class="panel-heading">Agenda</div>

<div class="panel-body">
                   {!! $calendar->calendar() !!}
               </div>
           </div>
       </div>
   </div>
</div>
@endsection

@section('adminlte_js')
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.9.0/moment.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/2.2.7/fullcalendar.min.js"></script>
<script src="{{asset('js/locale-all.js')}}"></script>
<script src="{{asset('js/pt-br.js')}}"></script>

{!! $calendar->script() !!}
@endsection

resources/views/funcionarios_form.blade.php
@extends('adminlte::page')

@section('title', 'Funcionarios')
@section('css')
<style media="screen">
  .container{
    max-width: 100%;
  }
</style>
@stop

@section('content_header')

<div class="container">

  <div class="row" style="margin-top: 10px">

  @if ($errors->any())
    <div class="col-sm-12 alert alert-danger">
      <ul>
      @foreach ($errors->all() as $error)
        <li>{{ $error }}</li>
      @endforeach
      </ul>
    </div>
  @endif

  <div class="col-sm-12">

  @if ($acao == 1)
    <h2>Inclusão de funcionarios</h2>
  @elseif ($acao == 2)
    <h2>Consulta de funcionarios</h2>
  @else
    <h2>Alteração de funcionarios</h2>
  @endif

  <a href="{{ route('funcionarios.index') }}" class="btn btn-info pull-right" role="button">
    Voltar</a>


  </div>
</div>

  @if ($acao == 1)
    <form action="{{ route('funcionarios.store') }}" method="POST">
  @elseif ($acao == 3)
    <form action="{{ route('funcionarios.update', $reg->id) }}" method="POST">
    {{ method_field('PUT') }}
  @endif

    {{ csrf_field() }}

    <div class="form-group">
      <label for="nome">Nome:</label>
      <input type="text" class="form-control" id="nome" name="nome"
             value="{{ $reg->nome or old('nome') }}">
    </div>

    <div class="form-group">
      <label for="sobrenome">Sobrenome:</label>
      <input type="text" class="form-control" id="sobrenome" name="sobrenome"
             value="{{ $reg->sobrenome or old('sobrenome') }}">
    </div>

    <div class="form-group">
      <label for="telefone">Telefone:</label>
      <input type="text" class="form-control telefone-mask" id="telefone" name="telefone"
             value="{{ $reg->telefone or old('telefone') }}">
    </div>

    <div class="form-group">
      <label for="genero">Gênero:</label>
      <select name="genero" id="genero" class="form-control">
          <option value="feminino" {{old('genero') == 'feminino' ? 'selected': ''}}>Feminino</option>
          <option value="masculino" {{old('genero') =='masculino' ? 'selected' : ''}}>Masculino</option>
      </select>
    </div>

    <div class="form-group">
      <label for="data_nascimento">Data de Nascimento:</label>
      <input type="date" class="form-control" id="data_nascimento" name="data_nascimento"
             value="{{ $reg->data_nascimento or old('data_nascimento') }}">
    </div>

    <div class="form-group">
      <label for="endereco">Endereço:</label>
      <input type="text" class="form-control" id="endereco" name="endereco"
             value="{{ $reg->endereco or old('endereco') }}">
    </div>

    <div class="form-group">
      <label for="numero">Número:</label>
      <input type="text" class="form-control" id="numero" name="numero"
             value="{{ $reg->numero or old('numero') }}">
    </div>

    <div class="form-group">
      <label for="complemento">Complemento:</label>
      <input type="text" class="form-control" id="complemento" name="complemento"
             value="{{ $reg->complemento or old('complemento') }}">
    </div>

    <div class="form-group">
      <label for="cep">Cep:</label>
      <input type="text" class="form-control cep" id="cep" name="cep"
             value="{{ $reg->cep or old('cep') }}">
    </div>

    <div class="form-group">
      <label for="email">E-mail:</label>
      <input type="text" class="form-control" id="email" name="email"
             value="{{ $reg->email or old('email') }}">
    </div>

    <div class="form-group">
      <label for="email">Salário:</label>
      <input type="text" class="form-control money" id="salario" name="salario"
             value="{{ $reg->salario or old('salario') }}">
    </div>

    <div class="form-group">
      <label for="email">Admitido em:</label>
      <input type="date" class="form-control" id="data_admissao" name="data_admissao"
             value="{{ $reg->data_admissao or old('data_admissao') }}">
    </div>

    <div class="form-group">
      <label for="email">Função:</label>
      <select name="funcao" id="funcao" class="form-control">
          <option value="depiladora" {{old('funcao') == 'depiladora' ?
           'selected': ''}}>Depiladora</option>
          <option value="massoterapeuta" {{old('funcao') =='massoterapeuta' ?
           'selected' : ''}}>Massoterapeuta</option>
      </select>
    </div>

    <div class="form-group">
      <!-- <label for="password" class="col-md-4 control-label">Senha:</label> -->
      <label for="password">Senha:</label>
      <input type="password" class="form-control" id="password" name="password"
             value="{{ $reg->password or old('password') }}">
    </div>

    @if($acao == 1 or $acao == 3)
      <button type="submit" class="btn btn-primary">Enviar</button>
      <button type="reset" class="btn btn-success">Limpar</button>
    @endif

  </form>

@stop

@section('js')
<script       src="https://code.jquery.com/jquery-3.3.1.min.js"
        integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
        crossorigin="anonymous"></script>
<script src="{{ asset('js/jquery.mask.min.js')}}"></script>
<script type="text/javascript">
$(document).ready(function(){
var SPMaskBehavior = function (val) {
  return val.replace(/\D/g, '').length === 11 ? '(00) 00000-0000' : '(00) 0000-00009';
},
spOptions = {
  onKeyPress: function(val, e, field, options) {
      field.mask(SPMaskBehavior.apply({}, arguments), options);
    }
};

$('.telefone-mask').mask(SPMaskBehavior, spOptions);
});
$('.cep').mask('00000-000');
 $('.money').mask('000.000.000.000.000,00', {reverse: true});
</script>
@stop

resources/views/funcionarios_lista.blade.php
@extends('adminlte::page')

@section('title', 'Funcionarios')

@section('content_header')

<div class="container">

  <div class="row" style="margin-top: 10px">
  <div class="col-sm-6">
    <h2>Cadastro de funcionarios</h2>
  </div>

  <div class="col-sm-4">
     <form method="POST"
           class="form-inline"
           action="{{ route('funcionarios.pesq') }}">
       {{ csrf_field() }}
       <input type="text" class="form-control"
              name="palavra"
              placeholder="Palavra do filtro"> &nbsp;
       <input type="submit" class="btn btn-success"
              value="Ok">
     </form>
  </div>

  <div class="col-sm-2">
      <a href="{{ route('funcionarios.index') }}"
         class="btn btn-warning" role="button">
          Todos</a>

      <a href="{{ route('funcionarios.create') }}"
         class="btn btn-info" role="button">
           Novo</a>
  </div>

  </div>

  @if (session('status'))
  <div class="alert alert-success">
      {{ session('status') }}
  </div>
  @endif

  <table class="table table-hover">
    <thead>
      <tr>
        <th>Nome</th>
        <th>Sobrenome</th>
        <th>Telefone</th>
        <th>E-mail</th>
        <th>Endereço</th>
        <th>Ações</th>
      </tr>
    </thead>
    <tbody>
      @forelse ($funcionarios as $u)
        <tr>
          <td>{{$u->nome}}</td>
          <td>{{$u->sobrenome}}</td>
          <td>{{$u->telefone}}</td>
          <td>{{$u->email}}</td>
          <td>{{$u->endereco}}</td>
          <td>
           <a href="{{ route('funcionarios.show', $u->id) }}"
              class="btn btn-success btn-sm" role="button">Consultar</a>

           <a href="{{ route('funcionarios.edit', $u->id) }}"
              class="btn btn-warning btn-sm" role="button">Alterar</a>

           <form method="POST" action="{{ route('funcionarios.destroy', $u->id) }}"
                 style="display: inline-block;"
                 onsubmit="return confirm('Confirma Exclusão?') ">
            {{ method_field('DELETE') }}
            {{ csrf_field() }}
              <button type="submit" class="btn btn-danger btn-sm">
                Excluir</button>
           </form>

          </td>
        </tr>
      @empty
        <tr><td colspan=5>
          Não há funcionarios cadastrados
          ou com a palavra <b>{{ $palavra or '' }}</b>
          informada na pesquisa </td></tr>
      @endforelse
    </tbody>
  </table>

</div>

@stop

resources/views/principal.blade.php
@yield(‘conteudo’)

resources/views/revisao.blade.php
@extends(‘principal’)
@section(‘conteudo’)
....
@endsection

resources/views/servicos_form.blade.php
@extends('adminlte::page')

@section('title', 'Consulta de Serviços')

@section('css')
<style media="screen">
  .container{
    max-width: 100%;
  }
</style>
@stop

@section('content_header')

<div class="container">

  <div class="row" style="margin-top: 10px">

  @if ($errors->any())
    <div class="col-sm-12 alert alert-danger">
      <ul>
      @foreach ($errors->all() as $error)
        <li>{{ $error }}</li>
      @endforeach
      </ul>
    </div>
  @endif

  <div class="col-sm-11">

  @if ($acao == 1)
    <h2>Inclusão de servicos</h2>
  @elseif ($acao == 2)
    <h2>Consulta de servicos</h2>
  @else
    <h2>Alteração de servicos</h2>
  @endif

  </div>
  <div class="col-sm-1">
  <a href="{{ route('servicos.index') }}" class="btn btn-info" role="button">
    Voltar</a>
  </div>
  </div>

  @if ($acao == 1)
    <form action="{{ route('servicos.store') }}" method="POST">
  @elseif ($acao == 3)
    <form action="{{ route('servicos.update', $reg->id) }}" method="POST">
    {{ method_field('PUT') }}
  @endif

    {{ csrf_field() }}

    <div class="form-group">
      <label for="nome">Nome:</label>
      <input type="text" class="form-control" id="nome" name="nome"
             value="{{ $reg->nome or old('nome') }}">
    </div>

    <div class="form-group">
      <label for="valor">Valor:</label>
      <input type="text" class="form-control money" id="valor" name="valor"
             value="{{ $reg->valor or old('valor') }}">
    </div>

    <div class="form-group">
      <label for="tempo_duracao">Duração:</label>
      <input type="text" class="form-control time" id="tempo_duracao" name="tempo_duracao"
             value="{{ $reg->tempo_duracao or old('tempo_duracao') }}">
    </div>

    <div class="form-group">
      <label for="descricao">Descrição:</label>
      <input type="text" class="form-control" id="descricao" name="descricao"
             value="{{ $reg->descricao or old('descricao') }}">
    </div>

    @if($acao == 1 or $acao == 3)
      <button type="submit" class="btn btn-primary">Enviar</button>
      <button type="reset" class="btn btn-success">Limpar</button>
    @endif

  </form>
@stop

@section('js')
<script       src="https://code.jquery.com/jquery-3.3.1.min.js"
        integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
        crossorigin="anonymous"></script>
<script src="{{ asset('js/jquery.mask.min.js')}}"></script>
<script type="text/javascript">
$(document).ready(function(){
var SPMaskBehavior = function (val) {
  return val.replace(/\D/g, '').length === 11 ? '(00) 00000-0000' : '(00) 0000-00009';
},
spOptions = {
  onKeyPress: function(val, e, field, options) {
      field.mask(SPMaskBehavior.apply({}, arguments), options);
    }
};

$('.telefone-mask').mask(SPMaskBehavior, spOptions);
});
$('.cep').mask('00000-000');
 $('.money').mask('000.000.000.000.000,00', {reverse: true});
 $('.time').mask('00:00:00');
</script>
@stop

resources/views/servicos_lista.blade.php
@extends('adminlte::page')

@section('title', 'Serviços')

@section('content_header')

<div class="container">

  <div class="row" style="margin-top: 10px">
  <div class="col-sm-6">
    <h2>Cadastro de servicos</h2>
  </div>

  <div class="col-sm-4">
     <form method="POST"
           class="form-inline"
           action="{{ route('servicos.pesq') }}">
       {{ csrf_field() }}
       <input type="text" class="form-control"
              name="palavra"
              placeholder="Palavra do filtro"> &nbsp;
       <input type="submit" class="btn btn-success"
              value="Ok">
     </form>
  </div>

  <div class="col-sm-2">
      <a href="{{ route('servicos.index') }}"
         class="btn btn-warning" role="button">
          Todos</a>

      <a href="{{ route('servicos.create') }}"
         class="btn btn-info" role="button">
           Novo</a>
  </div>

  </div>

  @if (session('status'))
  <div class="alert alert-success">
      {{ session('status') }}
  </div>
  @endif

  <table class="table table-hover">
    <thead>
      <tr>
        <th>Serviço</th>
        <th>Valor</th>
        <th>Duração</th>
        <th>Descrição</th>
        <th>Ações</th>
      </tr>
    </thead>
    <tbody>
      @forelse ($servicos as $p)
        <tr>
          <td>{{$p->nome}}</td>
          <td>{{$p->valor}}</td>
          <td>{{$p->tempo_duracao}}</td>
          <td>{{$p->descricao}}</td>
          <td>
           <a href="{{ route('servicos.show', $p->id) }}"
              class="btn btn-success btn-sm" role="button">Consultar</a>

           <a href="{{ route('servicos.edit', $p->id) }}"
              class="btn btn-warning btn-sm" role="button">Alterar</a>

           <form method="POST" action="{{ route('servicos.destroy', $p->id) }}"
                 style="display: inline-block;"
                 onsubmit="return confirm('Confirma Exclusão?') ">
            {{ method_field('DELETE') }}
            {{ csrf_field() }}
              <button type="submit" class="btn btn-danger btn-sm">
                Excluir</button>
           </form>

          </td>
        </tr>
      @empty
        <tr><td colspan=5>
          Não há servicos cadastrados
          ou com a palavra <b>{{ $palavra or '' }}</b>
          informada na pesquisa </td></tr>
      @endforelse
    </tbody>
  </table>

</div>

@stop

resources/views/usuarios_form.blade.php
@extends('adminlte::page')

@section('title', 'Clientes')
@section('css')
<style media="screen">
  .container{
    max-width: 100%;
  }
</style>
@stop
@section('content')
<div class="container">

  <div class="row" style="margin-top: 10px">

  @if ($errors->any())
    <div class="col-sm-12 alert alert-danger">
      <ul>
      @foreach ($errors->all() as $error)
        <li>{{ $error }}</li>
      @endforeach
      </ul>
    </div>
  @endif

  <div class="col-sm-11">

  @if ($acao == 1)
    <h2>Inclusão de Usuarios</h2>
  @elseif ($acao == 2)
    <h2>Consulta de Usuarios</h2>
  @else
    <h2>Alteração de Usuarios</h2>
  @endif

  </div>
  <div class="col-sm-1">
  <a href="{{ route('usuarios.index') }}" class="btn btn-info" role="button">
    Voltar</a>
  </div>
  </div>
</div>
<div class="container">
  <div class="row">
    <div class="col-md-12">
  @if ($acao == 1)
    <form action="{{ route('usuarios.store') }}" method="POST">
  @elseif ($acao == 3)
    <form action="{{ route('usuarios.update', $reg->id) }}" method="POST">
    {{ method_field('PUT') }}
  @endif

    {{ csrf_field() }}

    <div class="form-group">
      <label for="nome">Nome:</label>
      <input type="text" class="form-control" id="nome" name="nome"
             value="{{ $reg->nome or old('nome') }}">
    </div>

    <div class="form-group">
      <label for="sobrenome">Sobrenome:</label>
      <input type="text" class="form-control" id="sobrenome" name="sobrenome"
             value="{{ $reg->sobrenome or old('sobrenome') }}">
    </div>

    <div class="form-group">
      <label for="telefone">Telefone:</label>
      <input type="text" class="form-control telefone-mask" id="telefone" name="telefone"
             value="{{ $reg->telefone or old('telefone') }}">
    </div>

    <div class="form-group">
      <label for="genero">Gênero:</label>
      <select name="genero" id="genero" class="form-control">
          <option value="feminino" {{old('genero') == 'feminino' ? 'selected': ''}}>Feminino</option>
          <option value="masculino" {{old('genero') =='masculino' ? 'selected' : ''}}>Masculino</option>
      </select>
    </div>

    <div class="form-group">
      <label for="data_nascimento">Data de Nascimento:</label>
      <input type="date" class="form-control" id="data_nascimento" name="data_nascimento"
             value="{{ $reg->data_nascimento or old('data_nascimento') }}">
    </div>

    <div class="form-group">
      <label for="endereco">Endereço:</label>
      <input type="text" class="form-control" id="endereco" name="endereco"
             value="{{ $reg->endereco or old('endereco') }}">
    </div>

    <div class="form-group">
      <label for="numero">Número:</label>
      <input type="text" class="form-control" id="numero" name="numero"
             value="{{ $reg->numero or old('numero') }}">
    </div>

    <div class="form-group">
      <label for="complemento">Complemento:</label>
      <input type="text" class="form-control" id="complemento" name="complemento"
             value="{{ $reg->complemento or old('complemento') }}">
    </div>

    <div class="form-group">
      <label for="cep">Cep:</label>
      <input type="text" class="form-control cep" id="cep" name="cep"
             value="{{ $reg->cep or old('cep') }}">
    </div>

    <div class="form-group">
      <label for="email">E-mail:</label>
      <input type="text" class="form-control" id="email" name="email"
             value="{{ $reg->email or old('email') }}">
    </div>

    <div class="form-group">
      <!-- <label for="password" class="col-md-4 control-label">Senha:</label> -->
      <label for="password">Senha:</label>
      <input type="password" class="form-control" id="password" name="password"
             value="{{ $reg->password or old('password') }}">
    </div>

    @if($acao == 1 or $acao == 3)
      <button type="submit" class="btn btn-primary">Enviar</button>
      <button type="reset" class="btn btn-success">Limpar</button>
    @endif

  </form>
</div>
</div>
</div
@stop

@section('js')
<script       src="https://code.jquery.com/jquery-3.3.1.min.js"
        integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
        crossorigin="anonymous"></script>
<script src="{{ asset('js/jquery.mask.min.js')}}"></script>
<script type="text/javascript">
$(document).ready(function(){
var SPMaskBehavior = function (val) {
  return val.replace(/\D/g, '').length === 11 ? '(00) 00000-0000' : '(00) 0000-00009';
},
spOptions = {
  onKeyPress: function(val, e, field, options) {
      field.mask(SPMaskBehavior.apply({}, arguments), options);
    }
};

$('.telefone-mask').mask(SPMaskBehavior, spOptions);
});
$('.cep').mask('00000-000');

</script>
@stop

resources/views/usuarios_lista.blade.php
@extends('adminlte::page')

@section('title', 'Clientes')

@section('content_header')

<div class="container">

  <div class="row" style="margin-top: 10px">
  <div class="col-sm-6">
    <h2>Cadastro de Usuarios</h2>
  </div>

  <div class="col-sm-4">
     <form method="POST"
           class="form-inline"
           action="{{ route('usuarios.pesq') }}">
       {{ csrf_field() }}
       <input type="text" class="form-control"
              name="palavra"
              placeholder="Palavra do filtro"> &nbsp;
       <input type="submit" class="btn btn-success"
              value="Ok">
     </form>
  </div>

  <div class="col-sm-2">
      <a href="{{ route('usuarios.index') }}"
         class="btn btn-warning" role="button">
          Todos</a>

      <a href="{{ route('usuarios.create') }}"
         class="btn btn-info" role="button">
           Novo</a>
  </div>

  </div>

  @if (session('status'))
  <div class="alert alert-success">
      {{ session('status') }}
  </div>
  @endif

  <table class="table table-hover">
    <thead>
      <tr>
        <th>Nome</th>
        <th>Sobrenome</th>
        <th>Telefone</th>
        <th>E-mail</th>
        <th>Endereço</th>
        <th>Ações</th>
      </tr>
    </thead>
    <tbody>
      @forelse ($usuarios as $u)
        <tr>
          <td>{{$u->nome}}</td>
          <td>{{$u->sobrenome}}</td>
          <td>{{$u->telefone}}</td>
          <td>{{$u->email}}</td>
          <td>{{$u->endereco}}</td>
          <td>
           <a href="{{ route('usuarios.show', $u->id) }}"
              class="btn btn-success btn-sm" role="button">Consultar</a>

           <a href="{{ route('usuarios.edit', $u->id) }}"
              class="btn btn-warning btn-sm" role="button">Alterar</a>

           <form method="POST" action="{{ route('usuarios.destroy', $u->id) }}"
                 style="display: inline-block;"
                 onsubmit="return confirm('Confirma Exclusão?') ">
            {{ method_field('DELETE') }}
            {{ csrf_field() }}
              <button type="submit" class="btn btn-danger btn-sm">
                Excluir</button>
           </form>

          </td>
        </tr>
      @empty
        <tr><td colspan=5>
          Não há usuarios cadastrados
          ou com a palavra <b>{{ $palavra or '' }}</b>
          informada na pesquisa </td></tr>
      @endforelse
    </tbody>
  </table>

</div>

@stop